name: Terraform Drift Detection

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # Every day 3AM UTC

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan (Drift Check)
      run: terraform plan -no-color
