name: Terraform Drift Detection and Apply

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '28 13 * * *'  

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan (Drift Check)
      run: terraform plan -no-color

    - name: Terraform Apply (optional)
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
